parameters:
    polymer.configuration.class: Headzoo\Bundle\PolymerBundle\Config\PolymerConfiguration
    polymer.util.path_resolver.class: Headzoo\Bundle\PolymerBundle\Util\PathResolver
    
services:
    polymer.configuration:
        class: %polymer.configuration.class%
        # Arguments are added in PolymerExtension
        
        
    polymer.util.path_resolver:
        class: %polymer.util.path_resolver.class%
        arguments:
            - @polymer.configuration
            - @kernel